# Generated by Django 4.2.23 on 2026-05-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usado SOLO para pago único', max_digits=10),
        ),
    ]
