services:
  db:
    image: postgres:15
    container_name: mea_db
    restart: always
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: mea_user
      POSTGRES_PASSWORD: Choripan1324
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgadmin

  backend:
    build: .
    container_name: mea_backend

    depends_on:
      - db
    restart: always

    ports:
      - "8000:8000"

    env_file:
      - ./.env

    environment:
      - DJANGO_SETTINGS_MODULE=MEA.production

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn MEA.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./inventario-front
    container_name: mea_frontend

    ports:
      - "80:80"

    depends_on:
      - db
      - backend

    env_file:
      - ./.env

volumes:
  postgres_data: